user = [
    {
        "customerID": "5003-XZWWO",
        "gender": "Male",
        "SeniorCitizen": 0,
        "Partner": "Yes",
        "Dependents": "No",
        "tenure": 71,
        "PhoneService": "Yes",
        "MultipleLines": "Yes",
        "InternetService": "DSL",
        "OnlineSecurity": "No",
        "OnlineBackup": "Yes",
        "DeviceProtection": "Yes",
        "TechSupport": "Yes",
        "StreamingTV": "Yes",
        "StreamingMovies": "Yes",
        "Contract": "Two year",
        "PaperlessBilling": "No",
        "PaymentMethod": "Credit card (automatic)",
        "MonthlyCharges": 84.2,
        "TotalCharges": 5956.85,
    }
]

expercted_features = [
    {
        "gender_Female": 0.0,
        "gender_Male": 1.0,
        "SeniorCitizen_0": 1.0,
        "SeniorCitizen_1": 0.0,
        "Partner_No": 0.0,
        "Partner_Yes": 1.0,
        "Dependents_No": 1.0,
        "Dependents_Yes": 0.0,
        "PhoneService_No": 0.0,
        "PhoneService_Yes": 1.0,
        "MultipleLines_No": 0.0,
        "MultipleLines_No phone service": 0.0,
        "MultipleLines_Yes": 1.0,
        "InternetService_DSL": 1.0,
        "InternetService_Fiber optic": 0.0,
        "InternetService_No": 0.0,
        "OnlineSecurity_No": 1.0,
        "OnlineSecurity_No internet service": 0.0,
        "OnlineSecurity_Yes": 0.0,
        "OnlineBackup_No": 0.0,
        "OnlineBackup_No internet service": 0.0,
        "OnlineBackup_Yes": 1.0,
        "DeviceProtection_No": 0.0,
        "DeviceProtection_No internet service": 0.0,
        "DeviceProtection_Yes": 1.0,
        "TechSupport_No": 0.0,
        "TechSupport_No internet service": 0.0,
        "TechSupport_Yes": 1.0,
        "StreamingTV_No": 0.0,
        "StreamingTV_No internet service": 0.0,
        "StreamingTV_Yes": 1.0,
        "StreamingMovies_No": 0.0,
        "StreamingMovies_No internet service": 0.0,
        "StreamingMovies_Yes": 1.0,
        "Contract_Month-to-month": 0.0,
        "Contract_One year": 0.0,
        "Contract_Two year": 1.0,
        "PaperlessBilling_No": 1.0,
        "PaperlessBilling_Yes": 0.0,
        "PaymentMethod_Bank transfer (automatic)": 0.0,
        "PaymentMethod_Credit card (automatic)": 1.0,
        "PaymentMethod_Electronic check": 0.0,
        "PaymentMethod_Mailed check": 0.0,
        "tenure": 0.9859154929577465,
        "MonthlyCharges": 0.6551896207584831,
        "TotalCharges": 0.685212324024925,
    }
]
